---
# tasks file for ansible-patrol-prometheus-exporter
#


- name: "Copy files to the Patrol knowledge directory"
  copy:
    src: "knowledge/"
    dest: "{{ patrol_knowledge_directory }}"
    owner: "{{ patrol_user }}"
    group: "{{ patrol_group }}"
    mode: "u=rw,g=r,o=r"

- name: "Copy files to the Patrol psl directory"
  copy:
    src: "psl/"
    dest: "{{ patrol_psl_directory }}"
    owner: "{{ patrol_user }}"
    group: "{{ patrol_group }}"
    mode: "u=rw,g=r,o=r"
